### ISSUE TITLE
Nothing seen in logs

### ISSUE THREAD

**Issue by Morriz** [gerritjandebruin/ha-rtl#3]
Hi Gerrit-Jan, I have the same tuner, just another KaKu switch, the 8000a. The logs mention `Found Fitipower FC0012 tuner` so I assume it found the tuner. The 8000a info says it uses the same 433.92 MHz frequency, so the addon should be listening, right? Any ideas?

**Comment by Morriz** [comment]
So it creates the device just fine, but it just does not trigger anything. If I turn off your addon and instead turn on the rtl_433 addon afterwards and use this config it triggers:
```
frequency   433.915M
protocol    51

output mqtt://core-mosquitto:1883,user=xxx,pass=xxx,retain=true,devices=homeassistant/rtl433/action
# next line does not work and gives: mqtts (TLS) not available (
# output mqtts://core-mosquitto:8883,tls_cert=fullchain.pem,tls_key=privkey.pem,retain=true,devices=homeassistant/rtl433/action
report_meta time:iso:usec:tz
```

**Comment by Morriz** [comment]
So in essence I only used your run script to create the device, which might as well have been published in the "Developer Tools" with an `mqtt.publish` action. That way we can stay with upstream.

**Comment by gerritjandebruin** [comment]
Hi @Morriz ,

Sorry for the late answer.
I think it is indeed better to use the rtl_433 addon and configure the switch with MQTT autodiscovery (https://github.com/pbkhrv/rtl_433-hass-addons/tree/main/rtl_433_mqtt_autodiscovery or manual entry).

I will close this issue and archive this repo.

Thanks for reaching out!
